### ISSUE TITLE
error when running on windows

### ISSUE THREAD

**Issue by urbanhop** [JozoVilcek/gitbook-plugin-mermaid#15]
```
D:\dev\mybook>gitbook serve
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: loading book configuration....OK
info: load plugin gitbook-plugin-mermaid ....OK
info: load plugin gitbook-plugin-highlight ....OK
info: load plugin gitbook-plugin-search ....OK
info: load plugin gitbook-plugin-sharing ....OK
info: load plugin gitbook-plugin-fontsettings ....OK
info: load plugin gitbook-plugin-livereload ....OK
info: >> 6 plugins loaded
info: start generation with website generator
info: clean website generator
info: OK
D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_modules\phantom\
node_modules\dnode\node_modules\weak\node_modules\bindings\bindings.js:91
throw err
        ^
Error: Could not locate the bindings file. Tried:
ΓåÆ D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_modules\pha
ntom\node_modules\dnode\node_modules\weak\build\weakref.node
ΓåÆ D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_modules\pha
ntom\node_modules\dnode\node_modules\weak\build\Debug\weakref.node
ΓåÆ D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_modules\pha
ntom\node_modules\dnode\node_modules\weak\build\Release\weakref.node
ΓåÆ D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_modules\pha
ntom\node_modules\dnode\node_modules\weak\out\Debug\weakref.node
ΓåÆ D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_modules\pha
ntom\node_modules\dnode\node_modules\weak\Debug\weakref.node
ΓåÆ D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_modules\pha
ntom\node_modules\dnode\node_modules\weak\out\Release\weakref.node
ΓåÆ D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_modules\pha
ntom\node_modules\dnode\node_modules\weak\Release\weakref.node
ΓåÆ D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_modules\pha
ntom\node_modules\dnode\node_modules\weak\build\default\weakref.node
ΓåÆ D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_modules\pha
ntom\node_modules\dnode\node_modules\weak\compiled\0.12.0\win32\x64\weakref.node

    at bindings (D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node
_modules\phantom\node_modules\dnode\node_modules\weak\node_modules\bindings\bind
ings.js:88:9)
    at Object.<anonymous> (D:\dev\mybook\node_modules\gitbook-plugin-me
rmaid\node_modules\phantom\node_modules\dnode\node_modules\weak\lib\weak.js:7:35
)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at new D (D:\dev\mybook\node_modules\gitbook-plugin-mermaid\node_mo
dules\phantom\node_modules\dnode\index.js:28:20)
    at module.exports (D:\dev\mybook\node_modules\gitbook-plugin-mermai
d\node_modules\phantom\node_modules\dnode\index.js:8:12)

D:\dev\mybook>
```

do you have any suggestions what i should diagnose?
thx

**Comment by JozoVilcek** [comment]
Sorry, no clue :/ Maybe unfriendly versions of the `phantom` and  `phantomjs` libraries?

**Comment by urbanhop** [comment]
thank you.
it is no longer relevant to me, i will close this issue.

**Comment by FrenchBen** [comment]
I'm having the exact same issue as above - What recently changed?

Possible relevant error from PhantomJS:

```
PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /srv/gitbook/node_modules/gitbook-plugin-mermaid/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [=======================================-] 98% 0.0s
Received 12854K total.
Extracting tar contents (via spawned process)
Removing /srv/gitbook/node_modules/gitbook-plugin-mermaid/node_modules/phantomjs/lib/phantom
Copying extracted folder /srv/gitbook/node_modules/gitbook-plugin-mermaid/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1457481765650/phantomjs-1.9.8-linux-x86_64 -> /srv/gitbook/node_modules/gitbook-plugin-mermaid/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /srv/gitbook/node_modules/gitbook-plugin-mermaid/node_modules/phantomjs/lib/phantom/bin/phantomjs
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/srv/gitbook/node_modules/gitbook-plugin-mermaid/node_modules/phantom/node_modules/dnode/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
  SOLINK_MODULE(target) Release/obj.target/weakref.node
  SOLINK_MODULE(target) Release/obj.target/weakref.node: Finished
  COPY Release/weakref.node
cp: cannot open 'Release/obj.target/weakref.node' for reading: Invalid argument
weakref.target.mk:124: recipe for target 'Release/weakref.node' failed
make: *** [Release/weakref.node] Error 1
make: Leaving directory '/srv/gitbook/node_modules/gitbook-plugin-mermaid/node_modules/phantom/node_modules/dnode/node_modules/weak/build'
gitbook-plugin-mermaid@0.0.9 node_modules/gitbook-plugin-mermaid
├── q@1.1.2
├── phantomjs@1.9.19 (which@1.0.9, progress@1.1.8, kew@0.4.0, md5@2.0.0, request-progress@0.3.1, adm-zip@0.4.4, request@2.42.0, npmconf@2.1.1, fs-extra@0.23.1)
└── phantom@0.8.4 (win-spawn@2.0.0, traverse@0.6.6, shoe@0.0.15, dnode@1.2.2)
```
